// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package graph

const (
	// defaultPageSize is used in AllXxx query methods `args.PageSize`
	defaultPageSize = 25
)
