// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package graph

import (
	"context"

	"github.com/volatiletech/sqlboiler/queries/qm"
)

func AssertPermissions(ctx context.Context, verb string, subject interface{}, args interface{}, input interface{}) ([]qm.QueryMod, error) {
	mods := []qm.QueryMod{}
	return mods, nil
}
