// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package graph

import graphql "github.com/graph-gophers/graphql-go"

// Schema is the GraphQL schema
var Schema = `
scalar Time
scalar Int64

schema {
  query: Query
  mutation: Mutation
}

type Query {


  allComments(
    since: ID
    pageSize: Int!
    search: SearchCommentArgs
  ): CommentsCollection!

  commentByID(
    id: ID!
  ): Comment!


  allPosts(
    since: ID
    pageSize: Int!
    search: SearchPostArgs
  ): PostsCollection!

  postByID(
    id: ID!
  ): Post!

}

type Mutation {


  createComment(
    input: CreateCommentInput!
  ): Comment!

  updateCommentByID(
    id: ID!
    input: UpdateCommentInput!
  ): Comment!

  deleteCommentByID(
    id: ID!
  ): Comment!


  createPost(
    input: CreatePostInput!
  ): Post!

  updatePostByID(
    id: ID!
    input: UpdatePostInput!
  ): Post!

  deletePostByID(
    id: ID!
  ): Post!

}

type Comment {
	
		# Convenient GUID for react component @key attribute
		rowId: String!
		id: ID!
		postID: Int!
		author: String!
		body: String!
		notes: String
		createdAt: Time
		updatedAt: Time
		post: Post
}

type CommentsCollection {
	nodes: [Comment!]!
}

input CreateCommentInput {
	
	  postID: Int!
	  author: String!
	  body: String!
	  notes: String
}

input UpdateCommentInput {
	
	  postID: Int!
	  author: String!
	  body: String!
	  notes: String
}

input SearchCommentArgs {
	
	  postID: Int
	  author: String
	  body: String
	  notes: String
}

type Post {
	
		# Convenient GUID for react component @key attribute
		rowId: String!
		id: ID!
		title: String!
		author: String!
		body: String!
		notes: String
		createdAt: Time
		updatedAt: Time
		comments: CommentsCollection
}

type PostsCollection {
	nodes: [Post!]!
}

input CreatePostInput {
	
	  title: String!
	  author: String!
	  body: String!
	  notes: String
}

input UpdatePostInput {
	
	  title: String!
	  author: String!
	  body: String!
	  notes: String
}

input SearchPostArgs {
	
	  title: String
	  author: String
	  body: String
	  notes: String
}


`

var _ = graphql.MustParseSchema(Schema, &Resolver{})
