// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package graph

import (
	"strconv"
	"testing"

	graphql "github.com/graph-gophers/graphql-go"
	"github.com/stretchr/testify/assert"
)

func strptr(s string) *string {
	return &s
}

func bool2ptr(b bool) *bool {
	return &b
}

func base64ptr(b Base64) *Base64 {
	return &b
}

func floatptr(f float64) *float64 {
	return &f
}

func intptr(i int32) *int32 {
	return &i
}

func int64ptr(i Int64) *Int64 {
	return &i
}

func textptr(t Text) *Text {
	return &t
}

func timeptr(t graphql.Time) *graphql.Time {
	return &t
}

func TestQueryModSearch(t *testing.T) {
	testCases := []struct {
		givenInput          interface{}
		expectResultsLength int
	}{
		{
			givenInput:          (*searchCommentInput)(nil),
			expectResultsLength: 0,
		},
		{
			givenInput: &searchCommentInput{

				PostID: int2ptr(42),
				Author: strptr("lorem ipsum"), // string
				Body:   strptr("lorem ipsum"), // string
				Notes:  strptr("lorem ipsum"), // null.String
			},
			expectResultsLength: 0,
		},
		{
			givenInput:          (*searchPostInput)(nil),
			expectResultsLength: 0,
		},
		{
			givenInput: &searchPostInput{

				Title:  strptr("lorem ipsum"), // string
				Author: strptr("lorem ipsum"), // string
				Body:   strptr("lorem ipsum"), // string
				Notes:  strptr("lorem ipsum"), // null.String
			},
			expectResultsLength: 0,
		},
	}

	for i, tc := range testCases {
		t.Run(strconv.Itoa(i), func(t *testing.T) {
			result := QueryModSearch(tc.givenInput)
			assert.Len(t, result, tc.expectResultsLength)
		})
	}
}
