// Code generated by SQLBoiler (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package dbmodel

var TableNames = struct {
	Comment string
	Post    string
}{
	Comment: "comment",
	Post:    "post",
}
